{% set name = "finitediff" %}
{% set version = "0.6.2" %}
{% set sha256 = "c0ac3607c9f5211d6e9125f1a300422f85b3a898cb5d3c62185ec94affac2ab0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - {{ name }}
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs {{ name }}

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Finite difference weights for any derivative order on arbitrarily spaced grids'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
