{% set name = "finitediff" %}
{% set version = "0.6.4" %}
{% set sha256 = "f05aee767f20f9f8b10b419ee6eb4f4ee6e712b341e4944a0f7c9ffedbf61572" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - numpy
    - cython
  run:
    - python
    - scipy

test:
  imports:
    - {{ name }}
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs {{ name }} -k 'not test_locate_discontinuity__pool_discontinuity_approx'

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Finite difference weights for any derivative order on arbitrarily spaced grids
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
